const cardsData = {
  section1: [
    {
      id: 1,
      title: "Annatto",
      content: "Natural orange-red colorant from Bixa orellana seeds.",
      expandedContent: "Annatto is a natural food colorant extracted from the seeds of the Bixa orellana tree. It imparts a vibrant orange to reddish hue and is commonly used in products like cheeses (such as cheddar), margarine, and snacks. Besides coloring, annatto has mild antioxidant properties and is generally recognized as safe for consumption within regulated limits.",
      image: "/images/cheddar.png",
      overlayImage: "images/annatto.jpg",
    },
    {
      id: 2,
      title: "Curcumin",
      content: "Yellow pigment from turmeric.",
      expandedContent: "Curcumin is the principal curcuminoid derived from turmeric root. It gives turmeric its distinct yellow color and is valued for its antioxidant and anti-inflammatory benefits. In food production, curcumin is used to color mustards, butters, cheeses, and baked goods. It is considered safe at typical dietary levels.",
      image: "/images/curry.png",
      overlayImage: "/images/curcumin.jpg",
    },
    {
      id: 3,
      title: "Betanin",
      content: "Extracted from beets, adds strong red color.",
      expandedContent: "Betanin is a red pigment obtained from beetroots. It is water-soluble and used to impart a rich red or pink color to foods like ice cream, confectionery, and processed meats. Betanin is sensitive to heat and light but is considered a safe natural coloring agent in foods.",
      image: "/images/beetrood.jpg",
      overlayImage: "/images/betanin.jpg",
    },
    {
      id: 4,
      title: "Anthocyanins",
      content: "Blue-purple pigments found in berries.",
      expandedContent: "Anthocyanins are a group of naturally occurring pigments responsible for the red, purple, and blue colors in many fruits and vegetables, including berries, grapes, and eggplants. They also possess antioxidant properties and are used as natural food colorants, especially in beverages and sweets.",
      image: "/images/berries.jpg",
      overlayImage: "/images/anthocyanins.jpg",
    },
    {
      id: 5,
      title: "Carotenoids",
      content: "Orange pigments from carrots.",
      expandedContent: "Carotenoids are a class of pigments naturally found in carrots, sweet potatoes, and pumpkins. They produce yellow, orange, and red hues and include compounds like beta-carotene, which the body can convert into vitamin A. Carotenoids are used as safe natural food colorants with additional nutritional benefits.",
      image: "/images/carrots.jpg",
      overlayImage: "/images/carotenoids.jpg",
    },
    {
      id: 6,
      title: "Anthocyanins",
      content: "Purple pigments from red cabbage.",
      expandedContent: "Anthocyanins found in red cabbage are highly pH-sensitive pigments that change color depending on the acidity of their environment. They are widely used as natural food colorants and are also studied for their potential health-promoting properties due to their antioxidant activity.",
      image: "images/red_cabbage.jpg",
      overlayImage: "/images/anthocyanins_cabbage.jpg",
    },
  ],

  section2: [
    {
      id: 7,
      title: "Nitrites",
      content: "Used in cured meats to prevent bacteria and preserve color.",
      expandedContent: "Nitrites are added to cured meats like bacon and ham to inhibit the growth of harmful bacteria such as Clostridium botulinum. They also help maintain the pink color of meats and contribute to their characteristic flavor. Although concerns exist about nitrites forming nitrosamines, strict regulations limit their levels to ensure safety.",
      image: "images/bacon.jpg",
      overlayImage: "/images/nitrites.jpg",
    },
    {
      id: 8,
      title: "Calcium Propionate",
      content: "Added to breads to prevent mold and extend shelf life.",
      expandedContent: "Calcium propionate is a preservative commonly used in baked goods to prevent mold growth and spoilage. It works by inhibiting the growth of mold and some bacteria, helping to maintain product freshness. It is considered safe at approved concentrations and does not affect the flavor of bread.",
      image: "/images/bread.jpg",
      overlayImage: "/images/calcium_propionate.jpg",
    },
    {
      id: 9,
      title: "Sorbates",
      content: "Common in jams and cheeses to prevent yeast and mold growth.",
      expandedContent: "Sorbates, particularly potassium sorbate, are preservatives used to prevent the growth of molds, yeasts, and fungi in foods like cheeses, jams, and syrups. They extend the shelf life of products without significantly altering their taste or smell and are recognized as safe additives when used appropriately.",
      image: "/images/jam.jpg",
      overlayImage: "/images/sorbates.jpg",
    },
    {
      id: 10,
      title: "Sodium Benzoate",
      content: "Helps prevent spoilage in acidic drinks.",
      expandedContent: "Sodium benzoate is a preservative used mainly in acidic foods and beverages, such as sodas, fruit juices, and pickles. It prevents the growth of microorganisms that could cause spoilage. It is generally recognized as safe when used within regulatory limits, though high amounts should be avoided.",
      image: "/images/lemonade.jpg",
      overlayImage: "/images/sodium_benzoate.jpg",
    },
    {
      id: 11,
      title: "Sulfites",
      content: "Used in dried fruits to prevent browning and spoilage.",
      expandedContent: "Sulfites are compounds that help preserve the color and freshness of dried fruits, wines, and some processed foods. They prevent oxidative browning and microbial spoilage. While generally safe, sulfites can cause allergic reactions in sensitive individuals, particularly asthmatics.",
      image: "/images/canned_fruit.jpg",
      overlayImage: "/images/sulfites.jpg",
    },
    {
      id: 12,
      title: "Ascorbic Acid",
      content: "Vitamin C acts as an antioxidant to preserve flavor and color.",
      expandedContent: "Ascorbic acid, commonly known as vitamin C, is used in foods to prevent oxidation and maintain color and flavor. It acts as an antioxidant, extending the shelf life of fruit juices, canned fruits, and other products. It also contributes nutritional value as an essential vitamin.",
      image: "/images/fruit_juice.jpg",
      overlayImage: "/images/ascorbic_acid.jpg",
    },
  ],

  section3: [
    {
      id: 13,
      title: "Monosodium Glutamate",
      content: "Boosts umami flavor in snacks, soups, and processed foods.",
      expandedContent: "Monosodium glutamate (MSG) is a flavor enhancer that intensifies savory (umami) taste in foods. It is naturally present in foods like tomatoes and cheeses and is widely used in processed foods, soups, and snacks. Numerous studies confirm MSG is safe for the general population when consumed at normal dietary levels.",
      image: "images/chips.jpg",
      overlayImage: "/images/msg.jpg",
    },
    {
      id: 14,
      title: "Disodium Inosinate",
      content: "Often combined with MSG in instant noodles and savory snacks.",
      expandedContent: "Disodium inosinate is a flavor enhancer usually used alongside MSG to provide a strong umami taste in instant noodles, potato chips, and savory snacks. It is often derived from meat or fish sources and is safe for consumption within the levels found in foods.",
      image: "/images/instant_noodles.jpg",
      overlayImage: "/images/inosinate.jpg",
    },
    {
      id: 15,
      title: "Natural Glutamates",
      content: "Found in soy sauce, parmesan, tomatoes, enhancing savory taste.",
      expandedContent: "Natural glutamates occur in many foods like soy sauce, parmesan cheese, mushrooms, and ripe tomatoes. They are responsible for the umami flavor and are chemically identical to the glutamate found in MSG. Their presence enhances the savory profile of many traditional dishes worldwide.",
      image: "/images/soy_sauce.jpg",
      overlayImage: "/images/glutamates.jpg",
    },
    {
      id: 16,
      title: "Disodium Guanylate",
      content: "Flavor enhancer used with MSG in processed meats and soups.",
      expandedContent: "Disodium guanylate is a flavor enhancer that works synergistically with MSG to boost the savory taste of foods. It is commonly found in processed meats, canned soups, and snack foods. Although more expensive than MSG, it is potent in small quantities and considered safe for consumption.",
      image: "/images/processed_meat.jpg",
      overlayImage: "/images/guanylate.jpg",
    },
    {
      id: 17,
      title: "Yeast Extract",
      content: "Natural flavoring ingredient rich in umami, used in soups and snacks.",
      expandedContent: "Yeast extract is a natural flavoring made by breaking down yeast cells. It is rich in naturally occurring glutamates and provides a savory, umami flavor to soups, broths, sauces, and snacks. It is often used as a clean-label alternative to MSG.",
      image: "/images/cheese_snacks.jpg",
      overlayImage: "/images/yeast_extract.jpg",
    },
    {
      id: 18,
      title: "Hydrolyzed Vegetable Protein",
      content: "Adds umami flavor to soups, sauces, and bouillon cubes.",
      expandedContent: "Hydrolyzed vegetable protein (HVP) is made by breaking down plant proteins into their amino acids, resulting in a flavor-rich ingredient. It is commonly used in soups, sauces, seasonings, and bouillon cubes to enhance umami taste.",
      image: "/images/bouillon_cubes.jpg",
      overlayImage: "/images/hydrolyzed_protein.jpg",
    },
  ],

  section4: [
    {
      id: 19,
      title: "MSG is Dangerous",
      content: "Studies show MSG is safe when consumed within...",
      expandedContent: "Despite widespread myths, extensive research has shown that MSG is safe for the general population when consumed within normal dietary limits. Regulatory agencies like the FDA and WHO recognize MSG as a safe food ingredient.",
      image: "/images/msg.jpg",
      overlayImage: "/images/msg.jpg",
    },
    {
      id: 20,
      title: "Preservatives Are Always Harmful",
      content: "Preservatives protect food safety...",
      expandedContent: "Preservatives play a critical role in preventing spoilage and ensuring food safety. Regulatory agencies strictly control which preservatives are allowed and in what quantities, minimizing any potential health risks.",
      image: "/images/nitrites.jpg",
      overlayImage: "/images/nitrites.jpg",
    },
    {
      id: 21,
      title: "Natural Additives Are Always Safer",
      content: "Natural substances can be harmful...",
      expandedContent: "Natural additives are not automatically safer than synthetic ones. Toxicity depends on the substance and the dose. Even some natural compounds, like certain plant alkaloids, can be harmful if consumed in excess.",
      image: "/images/carrots.jpg",
      overlayImage: "/images/carrots.jpg",
    },
    {
      id: 22,
      title: "All E-numbers Are Dangerous",
      content: "E-numbers simply indicate approved food additives, not danger.",
      expandedContent: "E-numbers are a system used in Europe to identify approved food additives. An E-number indicates that the additive has been tested and found safe for use in foods, not that it is dangerous.",
      image: "/images/sorbates.jpg",
      overlayImage: "/images/sorbates.jpg",
    },
    {
      id: 23,
      title: "Food Dyes Always Cause Hyperactivity",
      content: "No conclusive evidence links food dyes directly...",
      expandedContent: "While some studies have suggested a possible link between artificial food dyes and hyperactivity in sensitive children, the evidence remains inconclusive. Regulatory bodies monitor and limit the use of such additives to ensure public safety.",
      image: "/images/fruit_juice.jpg",
      overlayImage: "/images/fruit_juice.jpg",
    },
    {
      id: 24,
      title: "Additives Always Cause Cancer",
      content: "Most additives are tested for...",
      expandedContent: "Food additives undergo rigorous testing before approval. The overwhelming majority show no cancer risk at dietary exposure levels. Proper regulation ensures that food additives contribute to safety, quality, and shelf life without posing health threats.",
      image: "/images/soy_sauce.jpg",
      overlayImage: "/images/soy_sauce.jpg",
    },
  ],
};

export default cardsData;
